[package]
name = "common"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bigdecimal = "0.4.5"
uuid = { version = "1.10.0", features = ["v7"] }
